version: '{build}'
image: Visual Studio 2015
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release

install:
  - ps: Start-FileDownload https://github.com/open-source-parsers/jsoncpp/archive/1.8.0.zip jsoncpp-1.8.0.zip
  - 7z x -bd -oC:\projects jsoncpp-1.8.0.zip
  - move C:\projects\jsoncpp-1.8.0 %APPVEYOR_BUILD_FOLDER%

before_build: 
  - cd %APPVEYOR_BUILD_FOLDER%
  - md build
  - cd build
  - if %PLATFORM% == x86 set GENERATOR="Visual Studio 14 2015"
  - if %PLATFORM% == x64 set GENERATOR="Visual Studio 14 2015 Win64"
  - cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\build\install\%APPVEYOR_PROJECT_NAME% ..

build_script:
  - msbuild %APPVEYOR_BUILD_FOLDER%\build\jsoncpp.sln /m /v:minimal
  - msbuild %APPVEYOR_BUILD_FOLDER%\build\INSTALL.vcxproj /m /v:minimal

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%\build\install
  - 7z a %APPVEYOR_PROJECT_NAME%.zip %APPVEYOR_PROJECT_NAME%
  - move %APPVEYOR_PROJECT_NAME%.zip %APPVEYOR_BUILD_FOLDER%

artifacts:
  - path: %APPVEYOR_PROJECT_NAME%.zip

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
