version: '{build}'
image: Visual Studio 2015
platform:
  - x86
  - x64
configuration:
  - Release
environment:
  PROJECT: jsoncpp
  CMAKE_PROJECT: jsoncpp
  VERSION: 1.8.0-1
  matrix:
    - LIBRARY_TYPE: static
    - LIBRARY_TYPE: dynamic

install:
  - ps: |
      Start-FileDownload https://github.com/open-source-parsers/jsoncpp/archive/1.8.0.zip jsoncpp-1.8.0.zip
      7z x -bd -oC:\projects jsoncpp-1.8.0.zip
      move C:\projects\jsoncpp-1.8.0 "C:\projects\${env:PROJECT}"

before_build: 
  - ps: |
      ${env:BUILD_DIRECTORY}="${env:APPVEYOR_BUILD_FOLDER}\build"
      ${env:INSTALL_DIRECTORY}="${env:APPVEYOR_BUILD_FOLDER}\${env:PROJECT}"
      New-Item -Path "${env:BUILD_DIRECTORY}" -ItemType "directory"
      cd "${env:BUILD_DIRECTORY}"
      
      ${generator} = "Visual Studio 14 2015"
      if(${env:PLATFORM} -eq "x64") { ${generator} = "${generator} Win64" }
      
      if(${env:LIBRARY_TYPE} -eq "static") { 
        ${library_flags} = "-DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF"
      }
      elseif(${env:LIBRARY_TYPE} -eq "dynamic") {
        ${library_flags} = "-DBUILD_STATIC_LIBS=OFF -DBUILD_SHARED_LIBS=ON"
      }
      
      cmake `
        -G "${generator}" `
        -DCMAKE_INSTALL_PREFIX="${env:INSTALL_DIRECTORY}" `
        "${library_flags}" `
        "C:\projects\${env:PROJECT}"

build_script:
  - ps: |
      msbuild "${env:BUILD_DIRECTORY}\${CMAKE_PROJECT}.sln" /m /v:minimal
      msbuild "${env:BUILD_DIRECTORY}\INSTALL.vcxproj" /m /v:minimal

after_build:
  - ps: |
      cd "${env:APPVEYOR_BUILD_FOLDER}"
      7z a "${env:PROJECT}_${env:VERSION}_${env:LIBRARY_TYPE}_${env:PLATFORM}.zip" "${env:PROJECT}"

artifacts:
  - path: $(PROJECT)_$(VERSION)_$(LIBRARY_TYPE)_$(platform).zip

deploy:
  release: v$(VERSION)
  description: "v$(VERSION)"
  provider: GitHub
  auth_token:
    secure: Stag2HnDJZFOF5/29yUlXQNlShCTIbAaAH/JLNnO7pb1AUIPGSnNJI4BykbCxVp2
  artifact: /.*\.zip/
  on:
    branch: master
    appveyor_repo_tag: true

